name: skaffold

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      environment_url:
        required: false
        type: string
      cmd:
        required: true
        type: string
      version:
        required: false
        type: string
        default: "1.39.4"
      sops:
        required: false
        type: boolean
        default: false
      vals:
        required: false
        type: boolean
        default: false
      use_private_charts:
        type: boolean
        required: false
        default: false
    secrets:
      token:
        required: true
      KUBECONFIG:
        required: true
      ENV_VARS:
        required: false

jobs:
  skaffold_deploy:
    runs-on: ubuntu-latest
    environment: 
        name: ${{ inputs.environment }}
        url: ${{ (inputs.environment_url != '' && inputs.environment_url ) || steps.deploy.outputs.environment_url }}
    steps:
      - name: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: docker - login container registry
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.token }}

      - uses: mdgreenwald/mozilla-sops-action@d9714e521cbaecdae64a89d2fdd576dd2aa97056
        if: inputs.sops

      - uses: jkroepke/setup-vals@495a61d4caadabb22c12180d7bf37e486107cb4a
        if: inputs.vals

      - uses: yokawasa/action-setup-kube-tools@9e25a4277af127b60011c95b6ed2da7e3b3613b1
        with:
          skaffold: ${{ inputs.version }}
  
      - uses: azure/k8s-set-context@212a19233d93f03eceaac31ae5a1d1acf650b6ef
        name: set kube context
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: configure helm repo
        id: helm_repo_config
        if: inputs.use_private_charts
        run: |
          helm repo add smartmedsa https://smartmedsa.github.io/helm-charts/
          helm repo update smartmedsa
          helm registry login ghcr.io -u ${{ github.actor }} -p ${{ secrets.token }}

      - name: deploy
        id: deploy
        env:
          SKAFFOLD_DETECT_MINIKUBE: "false"
          SKAFFOLD_UPDATE_CHECK: "false"
          ENV_VARS: ${{ secrets.ENV_VARS }}
        run: |
          set -o allexport
          source <(printenv ENV_VARS)
          set +o allexport
          
          ${{ inputs.cmd }}
        shell: bash
