
name: skaffold

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      workspace:
        required: true
        type: string
      cmd:
        required: true
        type: string
      helm_dir:
        required: false
        type: string
    secrets:
      token:
        required: true
      KUBECONFIG:
        required: true
      ENV_VARS:
        required: false
      INGRESS_HOST:
        required: false
      INGRESS_TARGET:
        required: false
      SKAFFOLD_KUBE_CONTEXT:
        required: false
      SKAFFOLD_NAMESPACE:
        required: false
        
jobs:
  skaffold_deploy:
    runs-on: ubuntu-latest
    env:
      WORKSPACE: ${{ inputs.workspace }}
      ENVIRONMENT: ${{ inputs.environment }}
    environment: ${{ inputs.environment }}
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: docker - login container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.token }}

      - uses: yokawasa/action-setup-kube-tools@v0.7.1
        with:
          setup-tools: |
            skaffold
          skaffold: 1.39.2

      - name: script - helm dependency update
        if: inputs.helm_dir
        run: |
          helm dependency update ${{ inputs.helm_dir }}

      - name: minikube start
        run: |
          minikube start --driver=docker
  
      - uses: azure/k8s-set-context@v2
        name: set kube context
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: deploy
        env:
          INGRESS_HOST: ${{ secrets.INGRESS_HOST }}
          INGRESS_TARGET: ${{ secrets.INGRESS_TARGET }}
          VARS: ${{ secrets.ENV_VARS }}
          NEXTAUTH_URL: ${{ secrets.INGRESS_HOST }}
          SKAFFOLD_KUBE_CONTEXT: ${{ secrets.SKAFFOLD_KUBE_CONTEXT }}
          SKAFFOLD_NAMESPACE: ${{ secrets.SKAFFOLD_NAMESPACE }}
          SKAFFOLD_UPDATE_CHECK: false
        run: |
          set -o allexport
          source <(printenv VARS)
          set +o allexport
          
          ${{ inputs.cmd }}
        shell: bash