
name: skaffold

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      workspace:
        required: true
        type: string
    secrets:
      token:
        required: true
      kubeconfig:
        required: false
jobs:
  skaffold_deploy:
    runs-on: ubuntu-latest
    environment:
      WORKSPACE: ${{ inputs.workspace }}
      ENVIRONMENT: ${{ inputs.environment }}
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: docker - login container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.token }}

      - uses: yokawasa/action-setup-kube-tools@v0.7.1
        with:
          setup-tools: |
            kubectl
            skaffold
          kubectl: 1.25.2
          skaffold: 1.39.2

      - name: deploy
        run: |
          echo hello
        shell: bash