
name: skaffold

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      workspace:
        required: true
        type: string
      cmd:
        required: true
        type: string
      helm_dir:
        required: false
        type: string
    secrets:
      token:
        required: true
      KUBECONFIG:
        required: true
      ENV_VARS:
        required: false

jobs:
  skaffold_deploy:
    runs-on: ubuntu-latest
    env:
      WORKSPACE: ${{ inputs.workspace }}
      ENVIRONMENT: ${{ inputs.environment }}
    environment: ${{ inputs.environment }}
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: docker - login container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.token }}
          
      - name: source env
        if: ${{ secrets.ENV_VARS }}
        env:
          VARS: ${{ secrets.ENV_VARS }}
        run: |
          set -o allexport
          source <(printenv VARS)
          set +o allexport

      - uses: yokawasa/action-setup-kube-tools@v0.7.1
        with:
          setup-tools: |
            kubectl
            helm
            skaffold
            kustomize
          helm: 3.10.0
          kubectl: 1.25.2
          skaffold: 1.39.2
          kustomize: 4.0.5

      - name: script - helm dependency update
        if: inputs.helm_dir
        run: |
          helm dependency update ${{ inputs.helm_dir }}

      - uses: azure/k8s-set-context@v2
        name: set kube context
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: deploy
        run: |
          ${{ inputs.cmd }}
        shell: bash
