name: skaffold

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      environment_url:
        required: false
        type: string
      cmd:
        required: true
        type: string
      version:
        required: false
        type: string
        default: "1.39.4"
      sops:
        required: false
        type: boolean
        default: false
    secrets:
      token:
        required: true
      KUBECONFIG:
        required: true
      ENV_VARS:
        required: false

jobs:
  skaffold_deploy:
    runs-on: ubuntu-latest
    environment: 
        name: ${{ inputs.environment }}
        url: ${{ (inputs.environment_url != '' && inputs.environment_url ) || steps.deploy.outputs.environment_url }}
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: docker - login container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.token }}

      - uses: mdgreenwald/mozilla-sops-action@v1.4.0
        if: inputs.sops

      - uses: yokawasa/action-setup-kube-tools@v0.9.2
        with:
          setup-tools: |
            skaffold
          skaffold: ${{ inputs.version }}
  
      - uses: azure/k8s-set-context@v3
        name: set kube context
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: deploy
        id: deploy
        env:
          SKAFFOLD_DETECT_MINIKUBE: "false"
          SKAFFOLD_UPDATE_CHECK: "false"
          ENV_VARS: ${{ secrets.ENV_VARS }}
        run: |
          set -o allexport
          source <(printenv ENV_VARS)
          set +o allexport
          
          ${{ inputs.cmd }}
        shell: bash
